baseURL = 'https://every2.github.io'
languageCode = 'pt-BR'
title = 'Every'
theme = "beautifulhugo"

[Params]

  subtitle = "Meu blog pessoal!"
  mainSections = ["post","posts"]
  favicon = "static/img/favicon.ico"
  dateFormat = "January 2, 2006"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Every"
  github = "Every2"

[[module.imports]]
  path = "github.com/halogenica/beautifulhugo"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3